name: update dependencies
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: NPM dependencies
      run: |
        npx npm-check-updates -u && npm i
        npm run build && rm -rf ./build
    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "feat: bump deps"
        branch: "update_deps"
        title: "feat: bump deps"
        labels: automated pr
        assignees: lafin
        reviewers: lafin
        team-reviewers: |
          owners
          maintainers
        milestone: 1
